carpentries/lesson-development-training

episodes/05-objectives.md
This PR matches the verbs.
I found this sentence a little hard to read.  Specifically I found optional phrase "and must do so before"  difficult to follow the sentence. After rereading it a couple of times without the phrase it made sense but wondering if we can move that phrase to make it easier to read?  Maybe to another sentence following?  
My best effort at rearranging but could still use some work.
> Before we can apply concepts and create something new, we must attain the ability to remember and distinguish between new concepts.  Remembering and distinguishing is also a task that is often faster to obtain then applying or creating.
=> fixing verb

learners/pilot-description.md
Adding the time and date links for the first time day of each session.  Lead me to realize I should warn people that the follow-up sessions are an hour earlier.
Sarah
=> Adding pilot timeanddate links

learners/trial-runs.md
Fixes #7
Provide information to trainees about the trial run task to be completed between the two parts of the training.
=> Add trial run info

episodes/26-collaborating.md
Resolves #119 
I did a bit of reading around various parts of the Internet, and the consensus is that the name comes from the idea that a maintainer would fetch & merge the changes proposed in the PR. This is slightly different from my original explanation, so I am correcting it here.
=> correct explanation of pull request name

episodes/11-formative-assessment.md
My understanding of minute cards is that they are the break time feedback that takes about a minute to complete.  In the Carpentries in-person workshops, we often use sticky notes for this purpose and then add an additional use for stickies by using them to get immediate feedback on pacing, learners needing help, and the speed of the workshop.  In my mind at least, that secondary use is separate and isn't the "minute card" purpose, because it has nothing to do with a minute, so I changed this bullet point name.  I'm not fully happy with the "checking in" name for this bullet point, might be a little informal.  Would appreciate other suggestions, or an argument for calling this point "minute cards" still.  Maybe "immediate feedback"?
Either way, I think we should still add the virtual …
=> renaming bullet and adding virtual example

episodes/20-preparing.md
Fixes #84
Replacing it with advice to use the 'Extract All Images' page of Workbench lesson sites.
=> Remove duplicate content about alt-text

episodes/24-collaborating.md, episodes/26-external.md
If merged, this will close #24
This feels like a long callout to put into the episode, but it is certainly useful information for developers. Perhaps I should add a Trainer Note above it, reminding Trainers not to go through this information in detail unless they find themselves with time to spare? Or would we be better off leaving it out altogether and perhaps adding this content elsewhere e.g. in the community handbook? And/or as a post on The Carpentries blog?
=> add callout about managing GH notifications

config.yaml, episodes/episode-objectives.md, episodes/episodes.md, episodes/infrastructure.md, episodes/objectives.md
Fixes #71 
Fixes #73 
Fixes #76 
This adds some more context and guidance to help trainees write objectives. 
It also (more importantly?) _adds a new episode_ (😱) about episodes,
addressing the problem identified in #73 where we had forgotten to get them to do this.
I think this only reflects what we did anyway in the pilots, so doesn't add teaching time in real terms,
but I acknowledge this may feel scary and would appreciate feedback! 😅
=> Add more context for objectives and episodes

README.md, episodes/collaborating.md, episodes/operations.md
Update slack links to point to the new domain URL and invite app.
=> Update slack links

episodes/audience.md, episodes/wrap-up2.md, links.md
Fixes #72 by adding guidance for Trainers at the start of the curriculum, recommending the use of [the Lesson Design Notes template](https://codimd.carpentries.org/HPwUE3FnTeSQJ9-_5EfU7Q?edit) by trainees throughout. I added a second note at the very end of part 2, with guidance Trainers can share with trainees if they want to include their design notes in their lesson site.
I can imagine a greater integration of the design notes document into the training, but that would be a much bigger PR (mentioning it in a lot of exercises, for example) and I think we should wait to see how well this works in the training before writing it into the curriculum.
=> Add trainer notes recommending use of lesson design notes template

episodes/exercises.md, episodes/formative-assessment.md
Fixes #219 by removing the largely redundant chunk of content about non-exercise types of formative assessment in _Designing Assessments_. I like the mention of _think, pair, share_ though, so have suggested to add that to the list in _Stay on Target_.
=> remove redundancy of content about formative assessment

episodes/infrastructure.md
Fixes #250 by adding a callout explaining differences between GitHub previews of (R) Markdown source files & the lesson content built from them.
=> Note differences between GitHub previews & lesson content

episodes/infrastructure.md
Fixes #246.
I remembered Ann asking about quotes around strings in last week's trainer training so I added an explanation on that - but feel like any text I add either opens another line of questions / further reading (e.g. mentioning of different data types in YAML) or is not 100% complete/correct (e.g. quoting strings is not the only way to deal with special/reserved characters in YAML).
=> Explanation on YAML key-value pairs.

episodes/infrastructure.md
Addresses https://github.com/carpentries/lesson-development-training/issues/247
Also: 
- Replaces 'email' with 'contact' as that is the value name in the current workbench template.  
- Provides guidance on what keywords to include.
=> 247 improve config exercise

episodes/operations.md
Fixes https://github.com/carpentries/lesson-development-training/issues/183
I made a couple of changes to the table proposed in #183. 
- moved "lesson owned by community" to top as it seemed to flow better to me
- changed "lesson stable" to be an X in the Incubator column and a check in the lab column
=> Add table with lesson development infrastructure overview

episodes/infrastructure.md
Also moved the description of 'Include all branches' where it naturally occurs in the config window.
Fixes #245.
=> Fixed label for 'Create repo from template' button. Fixes #245.

episodes/wrap-up3.md
Added a 20 minute exercise to reflect on best practices for collaborating on a lesson development project. This means we need to check if this addition fits within the schedule or something needs to be cut down.
Fixes #233.
Noticed some issue with lists within solution div not being renderred as expected. Bullet point lists without a empty like between points is renderred as one big block of text. Numbered lists are not showing numbers. Maybe it is just me missing some knowledge.
=> Added an exercise/top tips for collaboration

episodes/preparing.md
Fixes #86 by explaining where setup.md content appears in lesson site
=> Signpost location of rendered setup.md content

episodes/operations.md, links.md
Fixes #266 by trimming down the details of Incubator/Lab ecosystem. When it is ready, I will open a second PR to link to these details on a page at carpentries-incubator.org
=> Remove Incubator/Lab details from How We Operate

config.yaml, episodes/infrastructure.md
Fixes #78 by adding time for troubleshooting builds.
This PR moves the Episodes episode to the end of the first half-day, to allow time for the troubleshooting.
(#286 should be merged before this one. I will probably need to resolve conflicts.)
=> Add time for troubleshooting builds

episodes/infrastructure.md
Fixes #89 by adding a spoiler div at the end of the Workbench episode with some advice for troubleshooting a failed build process.
=> Add some website build troubleshooting tips

episodes/infrastructure.md
Fixes #182 by adding instruction to rename Rproj file
=> Mention Rproj file in lesson repo setup instructions

episodes/exercises.md, episodes/objectives.md
Resolves #28 by adding in some notes about how lesson design can be used to help when preparing to teach a workshop.
=> Add info about how prereq knowledge can be used for pilot workshops

CODE_OF_CONDUCT.md, episodes/introduction.md, episodes/reflecting.md, links.md
=> Reminder of workshop expectations

episodes/infrastructure.md
Fixes #242
Made a couple of small changes to move the gh-pages activation section to an instructor note.  Think the callout and adding to the about in settings is still relevant. 
I was a little conflicted. Since the `gh-pages` should be generated and autodetected by GitHub Pages as the branch to render, maybe this instructor note should be how to force the `gh-pages` branch to be build if you only have a `main` branch?
=> Moved gh-pages activation to instructor note

CODE_OF_CONDUCT.md
When I asked @sstevens2 to de-duplicate the link references in #291, I forgot that this Markdown file needs to be self-contained so that people can find the Code of Conduct from the repository. This PR re-adds the link to the CoC page as an inline link in the file.
=> inline link to CoC

episodes/formative-assessment.md
Added 2 more examples of misconceptions - on from "regular" life and one suggested by @sstevens2 from the "programming" world. Hopefully enough to give learners a start for the exercise that follows when they have to think of misconceptions from their experiences. It would have been nice to have a community-created list of misconceptions from past instructor training events that can be pointed to (something we could crowd-source at one of the trainers meetings perhaps?).
Once done, this will fix #177 and #181.
=> Added more examples of misconceptions and MCQs

AUTHORS.md, CITATION, CITATION.cff, README.md, config.yaml
- Adds a `CITATION.cff` file, listing everyone who has committed as an author (ordered alphabetically by family name)*
- Updates the `config.yaml` and `README.md` files to reflect the new status of the curriculum
- Removes the `AUTHORS.md` and `CITATION` files, rendered obsolete by the CFF file
\* in the next release (stable), the CFF specification should have been updated to allow for a `contributors` field, which we can use to list all the people (currently named in the README) who have contributed to the project but are not represented in the commit history.
=> Prepare beta release

episodes/infrastructure.md
In training today, @anenadic stumbled across an error in `infrastructure.md`, where it is stated that an episode file will be available after you add the source file but before you have included it in the list of episodes in `config.yaml`.
This PR fixes that by removing the relevant paragraph and adjusting the remaining content.
=> Fix description of episode adding process

links.md
There is a missing link to Incubator Proposals on https://carpentries.github.io/lesson-development-training/instructor/operations.html - adding it to links here in a hope it will fix this page by magic.
=> Added link to Incubator proposals

learners/trial-runs.md
Adjust the information about trial runs to reflect the guidance we have been giving collaborative groups during training events.
=> Update trial run info for groups

episodes/introduction.md
if the expected behaviour is that the link within these two callouts works the same:
- https://carpentries.github.io/lesson-development-training/aio.html#before-the-training-begins
- https://carpentries.github.io/instructor-training/01-welcome.html#before-the-course-begins
then, the link could be redirected to https://carpentries.github.io/instructor-training/icebreakers.html
=> fix icebreaker link

episodes/explanation.md, episodes/wrap-up2.md
Moved and renamed reflection exercise from https://carpentries.github.io/lesson-development-training/explanation.html to [wrap up after part 1](https://carpentries.github.io/lesson-development-training/wrap-up2.html). Also took an opportunity to swap the order of feedback and second reflection exercise in [wrap up after part 1](https://carpentries.github.io/lesson-development-training/wrap-up2.html).
Fixes #317 and #320.
=> Moved exercise on reflection to wrap up

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/suggest_improvement_1_lesson.yml, .github/ISSUE_TEMPLATE/suggest_improvement_2_episode.yml, .github/PULL_REQUEST_TEMPLATE.md
Closes #348 by adding templates for issues and PRs that are more relevant to this lesson repository than the standard templates provided at https://github.com/carpentries/.github/
=> Add issue & PR templates

config.yaml
FYI @anenadic @sstevens2 I am merging this as a step towards testing self-hosted web analytics for Carpentries lessons.
=> enable Matomo tracking for testing purposes

episodes/collaborating-newcomers.md, episodes/infrastructure.md
Closes #350 by updating content about lesson citation to reflect CFF as the default for new lessons.
=> Add content about CFF files for lesson citation

episodes/audience.md, episodes/episode-objectives.md, episodes/exercises.md, episodes/formative-assessment.md, episodes/wrap-up3.md, learners/misconceptions-mcqs.md, links.md
Fixes #336 
Closes #327
Resolves #330 
Some notes about what I am trying to achieve with this one.
1. Moves all "theory" around formative assessment and exercises into a single episode, cutting out most content on misconceptions. That content is not removed altogether, but relocated to an extra page in the _More_ dropdown, as optional further reading for people who want it.
2. Renames that "theory" episode to "Designing Assessments" and the second, "practical" episode "Implementing Exercises". This would render #327 obsolete.
3. Expands the "exercise types" exercise to talk about activities for lessons that are not primarily about coding skills - this is the part that still needs some work
4. If everything looks good when I am finished with the above, I will also update the branch to …
=> Reorganise content on formative assessment & exercises

episodes/infrastructure.md
Adding the title to the index page will result in it displaying underneath the "Summary and Setup" heading, which looks weird and doesn't follow the pattern used in our official lessons. The lesson title is already displayed in the lesson header for each episode.
=> remove instruction to add title

episodes/formative-assessment.md
An attempt to reorganise exercise types slightly and enable discussion around the issue  https://github.com/carpentries/lesson-development-training/issues/357. 
I have:
- reorganised the order of exercise types to put reflection style exercises towards the end of the list (as they mainly tend to come last in training) and 
- tried to fit in "problem solving" and "detecting misconception" exercises in there without mentioning code/non-code varieties (which I realised are probably not that important for our list).
=> Reorganising exercise types

episodes/audience.md, episodes/collaborating-newcomers.md, episodes/collaborating-team.md, episodes/episode-objectives.md, episodes/explanation.md, episodes/formative-assessment.md, episodes/infrastructure.md, episodes/narrative.md, episodes/operations.md, episodes/preparing.md, episodes/project-management.md, episodes/reflecting.md
This PR..
- updates the language in the callout about callouts to be a spoiler about spoilers
- makes many of the callouts into spoilers to indicate optional (spoiler) to teach vs vital (callout) to teach.
We might still need to find some place to talk about callouts.
Also recommend reviewing the rendered version of this PR since it will help you see where I kept the callouts vs switched them to spoilers.
=> Clarifying spoilers vs callouts and switching callouts to spoilers in this lesson

CITATION.cff
=> Expand author list in CITATION.cff and add references field

episodes/episodes.md, episodes/explanation.md, episodes/fig/cldt-structure.svg, episodes/formative-assessment.md, episodes/infrastructure.md, episodes/lesson-content.md
This is an attempt to update the estimated episode timings since #395 was merged. It also adjusts one of the exercises in `lesson-content` to be a bit more free-form, i.e. giving trainees some more time to explore the syntax and organisation of a Workbench lesson repository.
=> update timings and polish exercises

episodes/objectives.md, links.md
I think the positioning of this linkref, underneath some footnote references, was confusing things. Hopefully this will fix it.
=> Move computeBloom linkref

config.yaml
Matomo tracking was enabled in the core of varnish now, so we do not need this specific config any longer. Replacing with the general `analytics: carpentries` tracking config instead.
=> Unpin varnish version from my fork

episodes/infrastructure.md
=> Add summary table for lesson dev tasks in GH

episodes/collaborating-newcomers.md
=> remove mention of Hacktoberfest

episodes/collaborating-newcomers.md
Linking directly to the 'code' view will make these templates a little easier to use. We could link instead to the 'raw' view, if that would be easier?
=> Link to 'code' view of README/CONTRIBUTING templates

episodes/operations.md
Closes #54 by adding a spoiler div summarising the current state of lesson i18n in The Carpentries.
=> Add spoiler discussing current state of i18n for lessons

episodes/lesson-content.md
Resolves #457 by making clearer what keywords should be used for the `callout`, `spoiler`, and `caution` fenced divs.
=> Mention caution divs & include keywords for callout+spoiler fenced divs

episodes/collaborating-team.md
Fixes #463. 
Will crate a separate issue to create a diagram for a PR collaboration workflow.
=> Add the analogy of pull requests and editing a shared document

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/suggest_improvement_1_lesson.yml, .github/ISSUE_TEMPLATE/suggest_improvement_2_episode.yml, .github/PULL_REQUEST_TEMPLATE.md, CODE_OF_CONDUCT.md, links.md
The URL of The Carpentries Code of Conduct has changed since the launch of the revamped community handbook. This PR updates all of our links to point to the right page.
I am going to unilaterally merge this one, to bring us up to date ASAP.
=> Update links to Code of Conduct

episodes/collaborating-newcomers.md
Closes #444 by pointing the link to the new location of the Lesson Sprint Recommendations resource.
=> Replace link to Curriculum Development Handbook

CITATION.cff, README.md, config.yaml
Closes #419 by updating life cycle stage to stable. Also adjusts the CFF ready for release to Zenodo.
=> Mark as stable

episodes/lesson-content.md
We noticed today that the link currently takes people straight to the Windows install instructions, so this change points to a heading a little further up the page.
=> Slightly better anchor for Workbench setup instructions

episodes/lesson-content.md
Added some information about the workflow/package cache maintenance workflows, with a link to the instructions that people can follow to configure them for their repository.
=> link to setup instructions for maintenance workflows

episodes/introduction.md
We were given feedback at the previous training that the phrasing of the icebreaker exercise, asking trainees to think about _the best_ lesson they have followed, risked inducing "decision paralysis" as individuals might fixate on choosing a single "best" lesson instead of focusing on the follow-up questions. This PR adjusts the wording of the exercise to alleviate this problem.
=> Adjust icebreaker exercise

episodes/lesson-content.md
Fixes #442.
One place in our lesson to use this div (in addition to the section where we explain it) is where we draw attention to failed lesson builds. Or we can find a better place to use it naturally.
=> Expalin and add an example of a caution div

episodes/objectives.md
In recent trainings we have often needed to skip the _Reviewing Lesson Objectives_ exercise due to lack of time. This PR adds an Instructor Note guiding Trainers about how to do that gracefully.
=> Add Instructor Note about exercise
