episodes/03-audience.md

Think it would be good to make part 2b a little more specific.  I felt like "a questionnaire" might feel a little overwhelming.  They might only have time for 1-2 good MCQ questions.

adding specificity to part 2b

---

episodes/05-objectives.md

Thought maybe sharing their target audience info will help if their partner is not familiar with their audience.  Then made this a bundled PR with a language suggestion for the end of the sentence.  Can unpair and submit new PR if needed.

exercise lang change

---

episodes/11-exercises.md

Like to include reflection as it can be helpful for metacognition

adding reflection

---

episodes/03-audience.md

When I read this exercise I thought that many who are developing novice level experts might feel like their lesson has no prior knowledge needed.  Thought it might be good to suggest some skills that experts commonly overlook.  I'm a little concerned that these specifics might overwhelm the learners for this training so I'm not sure if it is needed or not and could use feedback from the group.

Adding a bit more text for novice level lessons

---

episodes/09-formative-assessment.md

Think it might be good to connect think about where misconceptions come from, aka prior knowledge that can get in the way.

adding outline point to connect with prior knowledge

---

links.md

Putting in a few common links I think we will need.

Some common links

---

episodes/09-formative-assessment.md

Grammar fix

---

episodes/02-lessons.md

Another short one, which I hope will only require a quick review.

draft Your Lessons episode

---

episodes/03-audience.md

Add mention of the differences in vocabulary and that in some domains the terms used in the lesson can mean something different.

mention differences in vocabulary

---

episodes/11-exercises.md
links.md

Here is my attempt to address [the concern I raised about explaining worked example effect in #41](https://github.com/carpentries/lesson-development-training/pull/41#discussion_r866802071). Please take a look and, if you like it, merge it into your branch for #41.

attempt to restructure worked example section

---

episodes/05-objectives.md
links.md

A first draft at the Objectives chapter.

drafting objectives episode content

---

episodes/03-audience.md
episodes/07-infrastructure.md

Adding key points that were missing for a couple of episodes

Key points

---

episodes/01-introduction.md
episodes/03-audience.md
episodes/05-objectives.md
learners/trial-runs.md

"chapter" -> "episode"

---

episodes/17-operations.md

describe life_cycle and carpentry config fields

---

episodes/26-collaborating.md

Fixes #105 by renaming episode to _Collaborating with Your Team_.

new title for collaborating-internal

---

episodes/24-external.md

add content about saying "no"

---

episodes/27-wrap-up3.md

Resolves #106 
Please take a look at the table and feel free to suggest any changes to that - it currently reflects only my opinion/experience.

add content about life cycle and expectations

---

episodes/26-collaborating.md

Added a small sub-section on Milestones and an exercise for Project Boards/Milestone.

Expanded the project management section. Added an exercise.

---

episodes/07-infrastructure.md

Add instructor note

---

episodes/17-explanation.md

This is the 2nd PR for #95 
Once #139 and this PR are merged then #95 can be closed.

Updating exercises based on pilot

---

episodes/15-narrative.md

Updates from issue #95 .  This only includes the first episode I taught. I will put in separate PRs for the other episodes I taught and changed.
I also updated these in the template CodiMD and will also update that before this gets merged with any additional changes.

Pilot updates to exercise and instructor notes

---

instructors/instructor-notes.md

Drafted a bit of text in the instructor notes on the reoccurring theme of piloting as a learning opportunity.
It is a very quick draft based on the issue so feedback highly welcome.  I was especially undecided if I should write it as a direct recommendation to the reader using "you" or not.
Closes #96

Adding instructor note about piloting to learn

---

episodes/05-objectives.md
links.md

add trainer note with markdown table template

---

episodes/07-infrastructure.md

Addresses #146 by removing numeric prefix from example episode file names and adding a step to add new episode files into the `config.yaml`

Update workbench episode

---

episodes/09-episode-objectives.md

link to Workbench component guide

---

episodes/17-explanation.md

link to Lab reviewer checklist

---

instructors/instructor-notes.md

Started building up the page of trainer notes

initialise Trainer Notes page

---

episodes/07-infrastructure.md

Added a small intro to README

---

AUTHORS.md
README.md

update README & AUTHORS

---

episodes/07-infrastructure.md

Updated the text to tell folks they can use the checkbox to add their website url
Fixes #186

Adding the info about using the checkbox

---

episodes/22-reflecting.md

Noted that the text was above the box here - not sure if this change is needed but I prefer it below.

moving welcome below overview box

---

episodes/07-infrastructure.md

Please delete this line and the text below before submitting your contribution.
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The …

Corrected typo

---

episodes/22-reflecting.md

add trainer note on format for trial run reflection discussion

---

episodes/17-explanation.md

provide more context, detail to reflection exercise

---

episodes/02-lesson-design.md
episodes/fig/cldt-design-process.svg
episodes/fig/nicholls-five-phases.svg

Fixes #168 
These are not particular exciting, but they serve a purpose.

Add lesson design process figures

---

episodes/explanation.md

Fixes #99 by adjusting the format of the group discussion activity, and adds a note for Trainers to guide them in facilitating the discussion.

Adjust format of discussion activity

---

episodes/narrative.md

Add a callout about varied examples and abstract concepts

---

episodes/introduction.md
links.md

Fixes #199 by adding some details about what trainees can expect to leave the training with.

Addressing expected outcomes at the beginning

---

episodes/collaborating-team.md

Making the changes from #256 directly to @anenadic's branch so they can be included when #258 is merged.

move info about protecting main branch to callout

---

episodes/collaborating-team.md

Section "Managing Communication" not rendering properly due to a missing line break before it.

Missing new line fix

---

episodes/project-management.md

Fixes #229 (and also the related https://github.com/carpentries/lesson-development-training/issues/197, https://github.com/carpentries/lesson-development-training/issues/195, https://github.com/carpentries/lesson-development-training/issues/138).

Update to milestones/boards section of project management

---

episodes/collaborating-newcomers.md
learners/reference.md

include a definition for "sprint"

---

episodes/exercises.md

Closes #81 by providing more guidance and clarity for [the _Assessing an Objective_ exercise](https://carpentries.github.io/lesson-development-training/13-exercises.html#exercise-assessing-an-objective-30-minutes).

add some more context and details for Assessing an Objective exercise

---

episodes/narrative.md

Fixes https://github.com/carpentries/lesson-development-training/issues/83

Add quote about explaining datasets

---

episodes/infrastructure.md

remind Trainers to show default version of lesson site

---

episodes/lesson-design.md

stress iterative nature of design process

---

episodes/explanation.md
episodes/formative-assessment.md
links.md

Adds more guidance for multiple choice questions.
Fixes #80 
Fixes #116

Expanded guidance for MCQ design

---

episodes/collaborating-team.md

Fixes #260 by discussing The Carpentries standard issue labels

Link to Carpentries issue labels

---

episodes/infrastructure.md

Fixes #249 by stressing importance of file extensions

Emphasise importance of including extension in episode filename

---

episodes/infrastructure.md

Fixes #243 by reminding Trainers to demonstrate how to edit files on GitHub

Remind Trainers to show how to edit files

---

episodes/formative-assessment.md

Ask trainees to identify misconceptions tested in MQC wrong answers

---

episodes/operations.md

Fixes #180
Let me know if you are okay with the way I linked the slide @anenadic found with this quote.

Adding quote from greg about lesson pilots

---

episodes/infrastructure.md

Fixes #241 
First try at incorperating the GitHub actions mention directly in the lesson.

Add showing GitHub Actions to lesson explicitly

---

episodes/episodes.md

Adds in the missing Questions, Objectives and Key Points blocks for the _Episodes_ episode.

Add missing Qs, Os, and KPs to Episodes episode

---

episodes/lesson-design.md

Fixes #306.
Nicholl should be Nicholls
Nicholl's should be Nicholls' or Nicholls's

Fixed spelling Nicholl -> Nicholls

---

episodes/lesson-design.md

Temporary double footnote fix

---

episodes/introduction.md

It takes a lot more than 15 minutes to complete the introduction for this training

Increase time required for Introduction

---

episodes/narrative.md

Oh, think we actually did mean lessons here instead of episodes. Or rather both!

'Lesson' used in place of 'episode'

---

episodes/narrative.md

Noticed this link was resolving 404, this appears to be correct.

Resolve broken link

---

episodes/formative-assessment.md

Removed LO not covered in the episode

---

episodes/formative-assessment.md

Fixes #325 by adjusting the order of the answer options.
Also fixes a mistake in one of the answers.

Update MCQ answer order

---

episodes/episode-objectives.md

Removed repeated exercise on prereq fenced div

---

episodes/exercises.md

Fixed exercise title

---

episodes/episodes.md

Just thought we should point out we want learners to think a bit on a higher level in this exercise, as there may have been confusion at the last workshop where they went a bit deeper and started working on episode objectives.

A small update to clarify the exercise on episodes

---

episodes/collaborating-newcomers.md
episodes/collaborating-team.md
episodes/project-management.md
learners/reference.md

Resolves #232 
Resolves #278 
Adds recommended reading sections to each of the collaboration skills episodes

Link to further reading resources in Collaborating* episodes

---

episodes/project-management.md

Fixing the broken links by directing to the new domain for the book

Update links to py-rse book

---

episodes/exercises.md

The exercise "Formatting Exercises in a Lesson Site" in the Exercises episode askes trainees to "format the MCQ you designed previously". However, the previous exercise it is referring to doesn't ask them to create an MCQ, but to create an exercise type of their choice.

Exercise doesn't have to be an MCQ

---

episodes/wrap-up2.md
learners/reference.md

Resolves #333 by moving some of the reflection prompts to a separate, optional homework exercise.

Adjust part 1 wrap-up

---

episodes/narrative.md

Closes #315 by adding a summary of our advice about choosing appropriate data and narratives

Summarise advice for data and narratives

---

episodes/preparing.md

Based on a need for clarification during training today

Add guidance on where to put teaching plan notes

---

episodes/objectives.md

Quick fix, @tobyhodges let me know if you were thinking of something else for this issue.
Fixes #221

adding blooms tax for compute

---

episodes/collaborating-team.md

Removed hanging link which is already embedded in the paragraph.

Remove hanging link

---

episodes/collaborating-newcomers.md

Fixes #391 by using the correct heading anchor.

adjust link target to use correct heading anchor

---

episodes/narrative.md

Add more example datasets and narratives

---

episodes/explanation.md
episodes/formative-assessment.md
episodes/lesson-design.md
episodes/objectives.md
episodes/preparing.md
episodes/reflecting.md

Fixes https://github.com/carpentries/lesson-development-training/issues/400

Update Nicholl's to Nicholls' throughout lesson

---

episodes/infrastructure.md
episodes/lesson-content.md

Fixes keypoints in lesson content and infrastructure episodes

---

episodes/infrastructure.md

Fixes R Markdown spelling

---

episodes/collaborating-newcomers.md

Fixes the URLs that I wrote incorrectly in #447

Fix URLS to template MDs

---

episodes/narrative.md

Resolves #82 by adding a callout to discuss where to store example data for a lesson.

add callout about data publication/storage

---

episodes/reflecting.md

Closes #387 bu adding Trainer Notes to _Reflecting on Trial Runs_ episode.

Add Trainer Notes on time management

---

episodes/project-management.md

Fixes #137.
Adds Sven's testimonial.
I had to do small tweaks and typo fixes to Sven's text, not sure this is a 100% quote - hope this is ok.
Another thing I noticed is I had to at * for italic text on each paragraph - so the source content will look a bit strange. Possibly there is a better way of doing this but no time to investigate.
We had another testimonial but never got the approval to publish it - I could try to contact the author again if we feel another one would be beneficial?

Add Sven's testimonial

---

episodes/fig/cldt-structure.svg

update figure to reflect latest structure

---

episodes/preparing.md

Adds a link to Pilot Operations Guide

---

episodes/narrative.md

Replace the Git story of Wolfman and Dracula with Alfredo the Chef

---

CITATION.cff
README.md
episodes/project-management.md

Closes #137 by quoting @rcurty alongside Sven in the Project Management & Governance episode.

Quote Renata's description of approach to project management

---

episodes/project-management.md

Adjust title of testimonial

---

episodes/lesson-content.md

Fixes a typo spotted by @sstevens2 while teaching

Prepreq -> prereq

---

episodes/narrative.md

The title of the FAIR RS course has changed slightly - changed it here to reflect the update.

Fix lesson title change

---

episodes/infrastructure.md

adding a little on permission options in github

---

episodes/preparing.md

related to issue #461 
Not sure if we want to close it or collect more feedback

Adding testimonials on trial run

---

episodes/narrative.md

Noticed this while Toby was teaching today.  Also needs to be updated in the codimd template

Updating link to bbrs workshop
